### PR TITLE
Show Inbox count in a red number

### PR DESCRIPTION
**Pull request by dfabulich**
image

image

### CODE REVIEW

**Comment by salty-horse** [comment]
I think it would look better vertically centered.

**Comment by dfabulich** [comment]
I played around with a few `vertical-align` options and preferred `top`. The default `vertical-align: baseline` looks like this:

image

That _is_ vertically centered, because the circle extends up and down below the baseline, but that makes the bottom of the circle appear below the baseline, which looks strange to me.

We could also go even higher with `vertical-align: super`, but I sense you might like that even less…?

image

**Comment by salty-horse** [comment]
On second thought, all 3 options look fine. This can be tweaked later based on feedback.

**Comment by alice-blue** [comment]
It's not that big a deal, but I'm not sure how I feel about the current size/alignment. If I look closely, it looks like it can't decide whether it wants to be a superscript (which would be both smaller and higher) or part of the regular text. 

It looks like Codespaces vertically centers the number of ports, which I think looks fine:

number in circle

**Pull request merged**
