### PR TITLE
Move time conversion functions to util.php

### PR DESCRIPTION
**Pull request by dfabulich**
They were being defined in an `if ($curuser)` section.

### CODE REVIEW

**Comment by dfabulich** [comment]
I'm not at all surprised that you had a hard time noticing this, because the code in `viewgame` is a total mess, especially with bizarre indentation as we constantly pop into and out of PHP tags.

I filed https://github.com/iftechfoundation/ifdb/issues/1020 to make this easier in the future.

**Comment by alice-blue** [comment]
It's telling me there are conflicts.

**Comment by dfabulich** [comment]
You're right! It conflicted with the merge. I'll get it

**Comment by dfabulich** [comment]
unconflicted

**Comment by alice-blue** [comment]
Thanks!

**Pull request merged**
